CREATE DATABASE YetiCave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE YetiCave;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name CHAR(64) NOT NULL UNIQUE,
  symbolic_code CHAR(128) NOT NULL
);

CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name CHAR(64) NOT NULL UNIQUE,
  description CHAR(128),
  lot_image CHAR(64) NOT NULL,
  start_price INT NOT NULL,
  date_close TIMESTAMP NOT NULL,
  bet_step INT NOT NULL
);

CREATE TABLE bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bet_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  bet_amount INT NOT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(128) NOT NULL UNIQUE,
  name CHAR(64) NOT NULL,
  password CHAR(64) NOT NULL,
  contact CHAR(128) NOT NULL
);
lotsusersusers